package com.homemade.ordapp.utils

const val ITEM_CHUNG_CAKE_SMALL = "CHUNG_CAKE_SMALL"
const val ITEM_CHUNG_CAKE_SMALL_INDEX = 0
const val ITEM_CHUNG_CAKE_NORMAL = "CHUNG_CAKE_NORMAL"
const val ITEM_CHUNG_CAKE_NORMAL_INDEX = 1
const val ITEM_CHUNG_CAKE_LARGE = "CHUNG_CAKE_LARGE"
const val ITEM_CHUNG_CAKE_LARGE_INDEX = 2

const val ITEM_PORK_SAUSAGE = "PORK_SAUSAGE"
const val ITEM_PORK_SAUSAGE_INDEX = 3
const val ITEM_PORK_SAUSAGE_LARGE = "PORK_SAUSAGE_LARGE"
const val ITEM_PORK_SAUSAGE_LARGE_INDEX = 4

const val ITEM_PORK_SAUSAGE_FRY = "PORK_SAUSAGE_FRY"
const val ITEM_PORK_SAUSAGE_FRY_INDEX = 5
const val ITEM_PORK_SAUSAGE_FRY_LARGE = "PORK_SAUSAGE_FRY_LARGE"
const val ITEM_PORK_SAUSAGE_FRY_LARGE_INDEX = 6

const val ORDER_STATUS_UNKNOWN = "UNKNOWN"
const val ORDER_STATUS_ORDERED = "ORDERED"
const val ORDER_STATUS_DELIVERED = "DELIVERED"
const val ORDER_STATUS_CANCELED = "CANCELED"

val sortOrderList = listOf(
    "CHUNG_CAKE_LARGE",
    "CHUNG_CAKE_NORMAL",
    "CHUNG_CAKE_SMALL",
    "PORK_SAUSAGE_LARGE",
    "PORK_SAUSAGE",
    "PORK_SAUSAGE_FRY"
)